services:
  flask-api:
    build: .
    container_name: flask-api
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "5000:5000"
      - "5001:5001"
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
