services:
  flask-api:
    build: ./flask-api
    container_name: flask-api 
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
