services:
  flask-api:
    build: .
    container_name: flask-api
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - "5001:5001"
    expose:
      - 5000
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
