services:
  flask-api:
    build: .
    container_name: flask-api
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 80
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
