# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataextraction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pulling_data_rtls import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 617)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 350, 181, 41))
        self.pushButton.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 251, 41))
        self.label.setStyleSheet("font: 75 10pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(220, 60, 261, 190))
        self.calendarWidget.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border:2px;\n"
"background-color: rgb(193, 193, 193);")
        self.calendarWidget.setObjectName("calendarWidget")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(350, 270, 118, 22))
        self.timeEdit.setTime(QtCore.QTime(16, 25, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.startlbl = QtWidgets.QLabel(self.centralwidget)
        self.startlbl.setGeometry(QtCore.QRect(230, 260, 101, 41))
        self.startlbl.setStyleSheet("font: 7pt \"Arial\";")
        self.startlbl.setObjectName("startlbl")
        self.endlbl = QtWidgets.QLabel(self.centralwidget)
        self.endlbl.setGeometry(QtCore.QRect(230, 300, 111, 41))
        self.endlbl.setStyleSheet("font: 7pt \"Arial\";")
        self.endlbl.setObjectName("endlbl")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(350, 310, 118, 22))
        self.timeEdit_2.setTime(QtCore.QTime(18, 5, 0))
        self.timeEdit_2.setObjectName("timeEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
 
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.button_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "confirm"))
        self.label.setText(_translate("MainWindow", "Select the date"))
        self.startlbl.setText(_translate("MainWindow", "Select the start time:"))
        self.endlbl.setText(_translate("MainWindow", "Select the end time:"))
    
    def button_clicked(self):
        timeing=get_unix_time(self.calendarWidget.selectedDate().year(),self.calendarWidget.selectedDate().month(),self.calendarWidget.selectedDate().day(),self.timeEdit.time().hour(),self.timeEdit.time().minute())
        print(timeing)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
